### ISSUE TITLE
Eliminar comentarios

### ISSUE THREAD

**Issue by Nidev-lab** [pablopaul01/Hotel-Backend#11]
Buenas! como va? encontre algunos comentarios en el codigo,

![image](https://github.com/pablopaul01/Hotel-Backend/assets/53904695/e6af9cc9-8a14-4d54-ad69-1015e0109289)

Recuerden, los comentarios no estan vistos como una buena practica , pero en si el codigo comentado es mucho menos aceptado.

Cualquier cosita podes contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by pablopaul01** [comment]
Buenas noches, realizamos los cambios. Quitamos los comentarios que habían quedado dentro del código.
